usuarios = [] 
while True:
    print ("Bem-vindo ao cadastro de usuário, por favor informe seus dados:")
    nome = input("Nome: ")
    cpf = int(input("CPF (Apenas digitos):"))
    data_nascimento = input ("Data de nascimento: ")
    logradouro = input ("Rua: ")
    numero = input ("Número: ")
    complemento = input ("Complemento: ")
    bairro = input ("Bairro: ")
    cidade_estado = input ("Cidade - Estado(Sigla): ")
    endereço = (logradouro + ", " + numero + ", " + complemento + ", " + bairro + ", " + cidade_estado)
    print (endereço)
    usuarios.append ({"nome": nome, "cpf": cpf, "nascimento": data_nascimento, "endereço": endereço})
    print(usuarios)        